I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 9, in script
    "Как-то раз, в первые дни лета 2017 года в одну квартиру на юге Нижнего Новгорода постучались." with disolve
  File "game/script.rpy", line 9, in <module>
    "Как-то раз, в первые дни лета 2017 года в одну квартиру на юге Нижнего Новгорода постучались." with disolve
NameError: name 'disolve' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 9, in script
    "Как-то раз, в первые дни лета 2017 года в одну квартиру на юге Нижнего Новгорода постучались." with disolve
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\ast.py", line 929, in execute
    say_menu_with(self.with_, renpy.game.interface.set_transition)
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\ast.py", line 748, in say_menu_with
    what = renpy.python.py_eval(expression)
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 9, in <module>
    "Как-то раз, в первые дни лета 2017 года в одну квартиру на юге Нижнего Новгорода постучались." with disolve
NameError: name 'disolve' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.1.3.23091805
2k17 1.0
Sun Jan  5 19:46:25 2025
